version: "3.8"
services:
  web:
    build: .
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "bewise"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: